<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var $this Mozg_Cielo_Block_Form_Oneclick */
?>
<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <?php
        $recurringDetails = $this->getRecurringDetails();
        if(isset($recurringDetails["variant"])):
        ?>

        <?php if(isset($recurringDetails["card_number"]) && isset($recurringDetails["card_expiryMonth"]) && isset($recurringDetails["card_expiryYear"]) ): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Credit Card Number') ?></label>
                <span>****</span> <?php echo $recurringDetails["card_number"]; ?>
            </div>

            <div class="columns three b">
                <label><?php echo $this->__('Expiration Date') ?><a href="#" id="update-expiration-date-<?php echo $_code; ?>" class="update-expiration-date"><?php echo $this->__('(update)') ?></a></label>

                <div id="static-card-expiry-<?php echo $_code; ?>" class="static-card-expiry">
                    <?php echo $recurringDetails["card_expiryMonth"] . " /" . $recurringDetails["card_expiryYear"]; ?>
                </div>
                <div id="changable-card-expiry-<?php echo $_code; ?>" class="changable-card-expiry" style="display:none;">
                    <select id="<?php echo $_code ?>_expiration_<?php echo $_code; ?>" <?php echo "name=\"payment[oneclick_exp_month]\""; ?> class="month validate-oneclick-exp required-entry">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$recurringDetails["card_expiryMonth"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>

                    <select id="<?php echo $_code ?>_expiration_yr_<?php echo $_code; ?>" <?php echo "name=\"payment[oneclick_exp_year]\""; ?> class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$recurringDetails["card_expiryYear"]): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

         <?php if( $this->showCvc()):?>
            <div class="columns three c">
                <label><?php echo $this->__('Card Verification Number') ?></label>
                <?php if($this->hasVerification()): ?>
                    <div class="cvc_block" id="cvc_block_<?php echo $_code;?>">
                        <input type="text" pattern="[0-9]{3,}" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" <?php echo "name=\"payment[oneclick_cid_".$_code."]\""; ?> value="" />
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php if($this->hasInstallments()): ?>
            <div id="mozg_cielo_api_oneclick_installment_<?php echo $_code;?>" class="mozg-cielo-oneclick-installments">
                <label for="<?php echo $_code ?>_installment_<?php echo $_code; ?>" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_installment" name="payment[installment]" class="mozg-installment number required-entry">
                            <?php foreach ($this->getInstallments() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        <?php endif;?>

        <?php elseif($recurringDetails["variant"] == "elv"): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Account holder name') ?></label>
                <span><?php echo $recurringDetails["elv_accountHolderName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('Account Number') ?></label>
                <span><?php echo $recurringDetails["elv_bankAccountNumber"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Bank Name') ?></label>
                <span><?php echo $recurringDetails["elv_bankName"]; ?></span>
            </div>
        <?php elseif($recurringDetails["variant"] == "openinvoice"): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Bank account holder name') ?></label>
                <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('Bank Account Number') ?></label>
                <span><?php echo $recurringDetails["bank_bankAccountNumber"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Country') ?></label>
                <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
            </div>
        <?php elseif($recurringDetails["variant"] == "sepadirectdebit" || $recurringDetails["variant"] == "ideal" ): ?>
            <div class="columns three a">
                <label><?php echo $this->__('Bank account holder name') ?></label>
                <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
            </div>
            <div class="columns three b">
                <label><?php echo $this->__('IBAN') ?></label>
                <span><?php echo $recurringDetails["bank_iban"]; ?></span>
            </div>
            <div class="columns three c">
                <label><?php echo $this->__('Country') ?></label>
                <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
            </div>
        <?php endif;?>
        <?php endif;?>
    </li>
</ul>
