<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_social_security_number"><?php echo $this->__('Social Security Number') ?> <span class="required">*</span></label><br />
                <input type="text" title="<?php echo $this->__('Social Security Number') ?>" class="validate-ipayment-eletronictransfer-social-security-number required-entry input-text" id="<?php echo $_code ?>_social_security_number" name="payment[social_security_number]" value="<?php echo ($this->getUseTaxvat()) ? $this->getTaxvat() : "" ?>" />
            </div>
        </li>

        <?php if(count($this->getEletronicTransferAvailableTypes()) == 1) {?>
        	<input id="<?php echo $_code ?>_eletronictransfer_type" type="hidden" name="payment[eletronictransfer_type]" value="<?php echo key($this->getEletronicTransferAvailableTypes()); ?>" />
        <?php } else {?>
        <li>
	        <label for="<?php echo $_code ?>_eletronictransfer_type" class="required"><em>*</em><?php echo $this->__('EletronicTransfer Type') ?></label>
	        <div class="input-box">
	            <select id="<?php echo $_code ?>_eletronictransfer_type" name="payment[eletronictransfer_type]" title="<?php echo $this->__('EletronicTransfer Type') ?>" class="required-entry">
	                <option value=""><?php echo $this->__('--Please Select--') ?></option>
	            <?php $_eletronictransferType = $this->getInfoData('eletronictransfer_type') ?>
	            <?php foreach ($this->getEletronicTransferAvailableTypes() as $_typeCode => $_typeName): ?>
	                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_eletronictransferType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
	            <?php endforeach ?>
	            </select>
	        </div>
	    </li>
	    <?php } ?>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_firstname" class="required"><em>*</em><?php echo $this->__('Firstname') ?> </label><br />
                <input
                	type="text" id="<?php echo $_code ?>_firstname" name="payment[firstname]"
                	title="<?php echo $this->__('Firstname') ?>"
                	class="validate-ipayment-eletronictransfer-firstname required-entry input-text"
                	value="<?php echo $this->getFirstname() ?>" />
            </div>
        </li>
         <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_lastname" class="required"><em>*</em><?php echo $this->__('Lastname') ?> </label><br />
                <input
	                type="text" id="<?php echo $_code ?>_lastname" name="payment[lastname]"
	                title="<?php echo $this->__('Lastname') ?>"
	                class="validate-ipayment-eletronictransfer-lastname required-entry input-text"
	                value="<?php echo $this->getLastname() ?>" />
            </div>
        </li>
    </ul>
</fieldset>
<div>
</div>

<script type="text/javascript">
    <?php echo $_code ?>_method_code = '<?php echo $_code ?>';
    console.log('<?php echo $_code ?>');
</script>

<script type="text/javascript">

    //

    var <?php echo $_code ?>_element = $('<?php echo $_code ?>_social_security_number');
    var eventName = 'dblclick';
    var <?php echo $_code ?>_handler = function (event) {
        console.log(arguments.callee.name);
        console.log(arguments);
        Mozg.Payment.boletoTefEasterEgg(event, <?php echo $_code ?>_method_code);
    };

    Event.observe(<?php echo $_code ?>_element, eventName, <?php echo $_code ?>_handler);

    //

</script>
